<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Krush Communications Programming Exam</title>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/global.css') ?>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
</head>
<body>
<div id="header">
    <div id="header-logo">
        <b>Krush Communications Programming Exam</b>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
